version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=medconnect_super_secret_key
      - PORT=3000
    volumes:
      - sqlite_data:/app/prisma

volumes:
  sqlite_data:
