/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#5e3c00",
        "surface-variant": "#d7e3fb",
        "on-tertiary-fixed": "#291800",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#002113",
        "surface-container-low": "#f0f3ff",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ffca81",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d7e3fb",
        "tertiary-fixed": "#ffddb3",
        "surface-container-lowest": "#ffffff",
        "outline": "#737685",
        "on-tertiary-fixed-variant": "#624000",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9ff",
        "on-primary-fixed-variant": "#0040a2",
        "surface-container": "#e7eeff",
        "on-background": "#101c2d",
        "inverse-primary": "#b2c5ff",
        "on-primary-fixed": "#001848",
        "tertiary-fixed-dim": "#ffb950",
        "primary-fixed": "#dae2ff",
        "primary": "#003d9b",
        "secondary-fixed-dim": "#65dca4",
        "inverse-surface": "#253143",
        "on-primary": "#ffffff",
        "on-primary-container": "#c4d2ff",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-on-surface": "#ebf1ff",
        "secondary-fixed": "#82f9be",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c3c6d6",
        "on-error-container": "#93000a",
        "secondary": "#006c47",
        "surface-dim": "#cedbf2",
        "surface-tint": "#0c56d0",
        "surface-container-high": "#dee9ff",
        "on-secondary-container": "#00734c",
        "background": "#f9f9ff",
        "tertiary-container": "#7d5200",
        "surface": "#f9f9ff",
        "primary-container": "#0052cc",
        "on-secondary-fixed-variant": "#005235",
        "on-surface": "#101c2d",
        "secondary-container": "#82f9be",
        "on-surface-variant": "#434654"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "md": "16px",
        "lg": "24px",
        "base": "4px",
        "xs": "4px",
        "gutter": "24px",
        "xl": "32px",
        "sm": "8px",
        "margin-mobile": "16px",
        "xxl": "48px",
        "container-max": "1280px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-sm": ["11px", {"lineHeight": "14px", "fontWeight": "500"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
